%% Import data from text file
% Script for importing data from the following text file:
%
%
% Auto-generated by MATLAB on 04-Jan-2021 18:20:22

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["ground_truth", "detected"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable("./data.csv", opts);


%% Clear temporary variables
clear opts
%%

plot(data.detected, data.ground_truth, 'o');
%%
x = data.detected;
y = data.ground_truth;