%% Import data from text file
% Script for importing data from the following text file:
%
%
% Auto-generated by MATLAB on 04-Jan-2021 18:20:22

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["ground_truth", "detected"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable("./webots_characterization.csv", opts);


%% Clear temporary variables
clear opts
%%

x = data.detected;
y = data.ground_truth;

%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 3' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Jan-2021 18:36:59


%% Fit: 'untitled fit 3'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'poly5' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
f=figure( 'Name', '5th degree polynomial' );
h = plot( fitresult, xData, yData );
legend( h, 'Ground truth vs. measured distance', '5th degree polynomial', 'Location', 'Best', 'Interpreter', 'none' );
% Label axes
xlabel( 'Measured distance', 'Interpreter', 'none' );
ylabel( 'Ground truth', 'Interpreter', 'none' );
grid on

exportgraphics(f, "interpolation.pdf", 'BackgroundColor', 'none', 'ContentType', 'vector');
