%% Import data from text file
% Script for importing data from the following text file:
%
% Auto-generated by MATLAB on 11-Jan-2021 10:20:37

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["est", "pose"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
datagyro = readtable("./data_gyro.csv", opts);
datafused = readtable("./data_fused.csv", opts);

datafused.pose = datafused.pose/3.14*180;
datagyro.pose = datagyro.pose/3.14*180;
datagyro.err = (datagyro.pose-datagyro.est);
datafused.err = (datafused.pose-datafused.est);

clear opts

%%

scatter(datagyro.pose, datagyro.est,'o','filled');
hold on

scatter(datafused.pose, datafused.est,'s','filled');
plot(-180:1:180, -180:1:180,'-k');


%%
f=figure();
stem(datagyro.pose,abs(datagyro.err),'o','filled');
hold on
stem(datafused.pose,abs(datafused.err),'s','filled');
ylabel("Estimate error");
legend("Gyroscope", "Gyroscope and encoders");
set(gca,'xticklabel',[])
set(gca,'ylim',[0 max([max(datagyro.err) max(datafused.err)])+2])
%%
exportgraphics(f, "sensor_fusion.pdf", 'BackgroundColor', 'none', 'ContentType', 'vector');
%%
disp(mean(datagyro.err.^2));
disp(mean(datafused.err.^2));
