%% Import data from text file
% Script for importing data from the following text file:
%
%
% Auto-generated by MATLAB on 05-Jan-2021 13:00:15

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["x", "y", "est_dx", "est_dy", "dx", "dy", "spostamento", "est_spostamento"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Import the data
log = readtable("./log.csv", opts);


clear opts
%%
x=log.est_dy;
y=log.spostamento;
plot(y, x,'x');