%% Import data from text file
% Script for importing data from the following text file:
%
% Auto-generated by MATLAB on 05-Jan-2021 09:23:05

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["distance", "measured_distance", "measured_angle"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "skip";

% Import the data
data = readtable("./after_interpolation.csv", opts);


% Clear temporary variables
clear opts
%% Boxplot distance
f=figure();
boxplot( data.measured_distance-data.distance);
title("Error on distance estimation");
ylabel("Distance error (m)");
exportgraphics(f, "distance_error.pdf", 'BackgroundColor', 'none', 'ContentType', 'vector');

%% Boxplot angle
f=figure();
boxplot( data.measured_angle);
title("Error on angle estimation");
ylabel("Angle error (degrees)");
exportgraphics(f, "angle_error.pdf", 'BackgroundColor', 'none', 'ContentType', 'vector');
%%
plot(data.measured_distance-data.distance, data.measured_angle,'o');
%%
f=figure();
Sigma = cov(data.measured_distance-data.distance, data.measured_angle);

% set the random seed:
randn('state',[2979743726;1541610269]);

% create a random sigma, mu:
mu = 0;

% compute, plot the cdf
[X,Y] = meshgrid(-1:.05:1);
XY = cat(3,X,Y);
% subtract mu
XYmmu = bsxfun(@minus,XY,shiftdim(mu(:),-2));

isigXY = squeeze(sum(bsxfun(@times,shiftdim(inv(Sigma),-2),XYmmu),3));
XYisXY = sum(isigXY .* XYmmu,3);

normcdf = (1/(2*pi*sqrt(det(Sigma)))) * exp(-0.5 * XYisXY);
surf(X,Y,normcdf);
xlabel("Distance error");
ylabel("Angle error");
%%
exportgraphics(f, "error_covariance_flat.pdf", 'BackgroundColor', 'none', 'ContentType', 'vector');
