%% Import data from text file
% Script for importing data from the following text file:
%
% Auto-generated by MATLAB on 07-Jan-2021 13:38:52

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["x", "y"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
deadreckoning = readtable("./dead_reckoning.csv", opts);
groundtruth = readtable("./ground_truth.csv", opts);


clear opts
%% trajectories
f = figure();
plot(deadreckoning.x, deadreckoning.y,'-r');
hold on
plot(groundtruth.x, groundtruth.y,'k');
xlabel('x')
ylabel('y')
legend('Dead reckoning','Ground truth','Location','SouthWest');
exportgraphics(f, "trajectories.pdf", 'BackgroundColor', 'none', 'ContentType', 'vector');
%% error
f=figure();
x = [0
    10.0
    19.5
    28.5
    37.0
    45.0
    52.5
    59.5
    66.0
    72.0
    77.5
    87.5]';
plot(x, deadreckoning.x - groundtruth.x);
hold on
plot(x, deadreckoning.y- groundtruth.y);
xlabel('Distance traveled')
ylabel('Dead reckoning error')
legend('X error','Y error')

exportgraphics(f, "dead_reckoning_error.pdf", 'BackgroundColor', 'none', 'ContentType', 'vector');

